/**
 * Static blog renderer. Generates:
 *   - public/blog/index.html
 *   - public/blog/rss.xml   (RSS 2.0)
 *   - public/blog/atom.xml  (Atom 1.0)
 * Run: npm run build:blog
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { posts, type BlogPost } from './posts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SITE = 'https://starstore.app';
const OUT_DIR = join(__dirname, '..', '..', 'public', 'blog');
const OUT_HTML = join(OUT_DIR, 'index.html');
const OUT_RSS = join(OUT_DIR, 'rss.xml');
const OUT_ATOM = join(OUT_DIR, 'atom.xml');

const escape = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');

const fmtDate = (iso: string) =>
  new Date(iso).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

const sorted = [...posts].sort((a, b) => (a.date < b.date ? 1 : -1));
const latestDate = sorted[0]?.date ?? new Date().toISOString();
const postUrl = (slug: string) => `${SITE}/blog/${slug}`;

/* ------------------------------ HTML ------------------------------ */

const tocHtml = sorted
  .map(
    (p, i) => `
        <a href="/blog/${escape(p.slug)}" class="toc-item group">
          <span class="toc-num">${String(i + 1).padStart(2, '0')}</span>
          <span class="toc-body">
            <span class="toc-title">${escape(p.title)}</span>
            <span class="toc-meta">${fmtDate(p.date)} · ${p.readMinutes} min</span>
          </span>
          <svg class="toc-arrow" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
        </a>`,
  )
  .join('');

const articlesHtml = sorted
  .map(
    (p: BlogPost, i: number) => `
      <article id="${escape(p.slug)}" class="post-card scroll-mt-28" itemscope itemtype="https://schema.org/BlogPosting">
        <meta itemprop="datePublished" content="${escape(p.date)}" />
        <meta itemprop="author" content="StarStore" />
        <div class="post-index">Article ${String(i + 1).padStart(2, '0')} / ${String(sorted.length).padStart(2, '0')}</div>
        <header class="post-header">
          <div class="post-tags">
            ${p.tags.map((t) => `<span class="tag">${escape(t)}</span>`).join('')}
          </div>
          <h2 class="post-title" itemprop="headline">${escape(p.title)}</h2>
          <p class="post-desc" itemprop="description">${escape(p.description)}</p>
          <div class="post-meta">
            <span class="avatar" aria-hidden="true">★</span>
            <span><strong>StarStore Team</strong></span>
            <span class="dot">·</span>
            <time datetime="${escape(p.date)}">${fmtDate(p.date)}</time>
            <span class="dot">·</span>
            <span>${p.readMinutes} min read</span>
          </div>
        </header>
        <div class="post-body prose-custom" itemprop="articleBody">
          ${p.bodyHtml}
        </div>
        <footer class="post-footer">
          <a href="#top" class="link-soft">↑ Back to top</a>
          <a href="https://t.me/TgStarStore_bot" class="link-cta">Open StarStore in Telegram →</a>
        </footer>
      </article>`,
  )
  .join('');

const blogJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'Blog',
  name: 'StarStore Insights',
  description: 'Guides, updates, and expert insights on Telegram Stars, Premium, and the StarStore platform.',
  url: `${SITE}/blog/`,
  publisher: { '@type': 'Organization', name: 'StarStore', url: SITE },
  blogPost: sorted.map((p) => ({
    '@type': 'BlogPosting',
    headline: p.title,
    description: p.description,
    datePublished: p.date,
    author: { '@type': 'Organization', name: 'StarStore' },
    url: postUrl(p.slug),
    mainEntityOfPage: postUrl(p.slug),
  })),
};

const breadcrumbsLd = {
  '@context': 'https://schema.org',
  '@type': 'BreadcrumbList',
  itemListElement: [
    { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE}/` },
    { '@type': 'ListItem', position: 2, name: 'Blog', item: `${SITE}/blog/` },
  ],
};

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Generated by src/blog/build.ts. Do not edit by hand. -->
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>StarStore Insights — Guides, Updates & News on Telegram Stars</title>
  <meta name="description" content="In-depth guides, platform updates, and expert insights on Telegram Stars, Premium subscriptions, and the StarStore Mini App. All posts on one page." />
  <meta name="keywords" content="Telegram Stars, Telegram Premium, sell Telegram stars, buy Telegram stars, USDT, TON blockchain, StarStore blog" />
  <meta name="author" content="StarStore" />
  <meta name="theme-color" content="#ffffff" />
  <meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1" />
  <meta name="googlebot" content="index, follow" />

  <link rel="canonical" href="${SITE}/blog/" />
  <link rel="alternate" type="application/rss+xml" title="StarStore Insights (RSS)" href="${SITE}/blog/rss.xml" />
  <link rel="alternate" type="application/atom+xml" title="StarStore Insights (Atom)" href="${SITE}/blog/atom.xml" />

  <meta property="og:type" content="website" />
  <meta property="og:url" content="${SITE}/blog/" />
  <meta property="og:title" content="StarStore Insights — Telegram Stars Guides & Updates" />
  <meta property="og:description" content="Guides, updates, and expert insights on Telegram Stars and the StarStore platform — all in one place." />
  <meta property="og:image" content="${SITE}/favicon.png" />
  <meta property="og:site_name" content="StarStore" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:url" content="${SITE}/blog/" />
  <meta name="twitter:title" content="StarStore Insights — Telegram Stars Guides & Updates" />
  <meta name="twitter:description" content="Guides, updates, and expert insights on Telegram Stars and the StarStore platform." />
  <meta name="twitter:image" content="${SITE}/favicon.png" />

  <!-- Google tag (gtag.js) -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-HJ1ZPZ1R7C"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-HJ1ZPZ1R7C');
  </script>

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Instrument+Serif&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="/css/blog.css" />
  <link rel="icon" type="image/png" href="/favicon.png" />

  <script type="application/ld+json">${JSON.stringify(breadcrumbsLd)}</script>
  <script type="application/ld+json">${JSON.stringify(blogJsonLd)}</script>
</head>
<body id="top">

  <header class="site-header">
    <div class="container header-row">
      <a href="/blog/" class="brand">
        StarStore <span class="brand-section">Insights</span>
      </a>
      <nav class="site-nav" aria-label="Primary">
        <a class="nav-link" href="/">Home</a>
        <a class="nav-link" href="/about">About</a>
        <a class="btn-login" href="https://t.me/TgStarStore_bot">Open app</a>
        <button class="menu-btn" aria-label="Menu" aria-expanded="false" aria-controls="mobile-nav">
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
        </button>
      </nav>
    </div>
    <nav id="mobile-nav" class="mobile-nav" aria-label="Mobile" hidden>
      <a class="mobile-nav-link" href="/">Home</a>
      <a class="mobile-nav-link" href="/about">About</a>
      <a class="mobile-nav-link" href="https://t.me/TgStarStore_bot">Open app</a>
    </nav>
  </header>

  <main class="main">
    <section class="container-narrow hero">
      <div class="hero-eyebrow">Introducing StarStore Insights</div>
      <h1 class="hero-title">Guides &amp; updates from the StarStore team</h1>
      <p class="hero-sub">Practical know-how for buying and selling Telegram Stars, growing referrals, and staying secure — written by the people who build the platform.</p>
      <div class="hero-actions">
        <a class="btn btn-primary" href="https://t.me/TgStarStore_bot">Open the app</a>
        <a class="btn btn-ghost" href="/blog/starstore-now-on-starstore-app">Read articles</a>
      </div>

      <div class="feed-strip" role="group" aria-label="Subscribe to the feed">
        <code id="feed-url">${SITE}/blog/rss.xml</code>
        <button class="btn-copy" type="button" data-copy="${SITE}/blog/rss.xml">Copy</button>
      </div>
      <p class="feed-caption">Paste into your feed reader to subscribe</p>

      <div class="compat">
        <div class="compat-label">In this edition</div>
        <div class="compat-grid">
          <span><i class="dotmark"></i>Announcements</span>
          <span><i class="dotmark"></i>Selling Stars</span>
          <span><i class="dotmark"></i>Knowledge base</span>
          <span><i class="dotmark"></i>Telegram guides</span>
        </div>
      </div>
    </section>

    <section class="container-narrow toc" id="articles" aria-labelledby="toc-heading">
      <div class="toc-head">
        <h2 id="toc-heading">In this issue</h2>
        <span class="toc-count">${sorted.length} posts · Updated ${fmtDate(latestDate)}</span>
      </div>
      <div class="toc-list">${tocHtml}
      </div>
    </section>

    <div class="container-narrow">
      <div class="posts">
${articlesHtml}
      </div>

      <section class="cta-card">
        <h2>Stay in the loop</h2>
        <div class="cta-actions">
          <a class="btn btn-primary" href="https://t.me/TgStarStore_bot">Join us on Telegram</a>
          <a class="btn btn-ghost" href="/blog/atom.xml">Atom feed</a>
        </div>
      </section>
    </div>
  </main>

  <footer class="site-footer">
    <div class="container footer-grid">
      <div>
        <div class="brand">StarStore <span class="brand-section">Insights</span></div>
        <p class="muted">Your trusted platform for Telegram Stars and Premium subscriptions.</p>
      </div>
      <div>
        <h4>Explore</h4>
        <ul><li><a href="/">Home</a></li><li><a href="/about">About</a></li><li><a href="/blog/">Insights</a></li></ul>
      </div>
      <div>
        <h4>Services</h4>
        <ul><li><a href="/">Buy Stars</a></li><li><a href="/sell">Sell Stars</a></li><li><a href="/referral">Referrals</a></li></ul>
      </div>
      <div>
        <h4>Feeds</h4>
        <ul><li><a href="/blog/rss.xml">RSS</a></li><li><a href="/blog/atom.xml">Atom</a></li><li><a href="/sitemap.xml">Sitemap</a></li></ul>
      </div>
    </div>
    <div class="container footer-bottom muted">© ${new Date().getFullYear()} StarStore. All rights reserved.</div>
  </footer>

  <a href="#top" class="back-to-top" aria-label="Back to top">↑</a>

  <script>
    const legacyAnchors = new Map([
      ${sorted.map((p) => `['#${escape(p.slug)}', '/blog/${escape(p.slug)}']`).join(',')}
    ]);
    if (legacyAnchors.has(window.location.hash)) {
      window.location.replace(legacyAnchors.get(window.location.hash));
    }

    // Smooth scroll
    document.querySelectorAll('a[href^="#"]').forEach(a => {
      a.addEventListener('click', e => {
        const href = a.getAttribute('href');
        if (!href || href === '#') return;
        const id = href.slice(1);
        const t = document.getElementById(id);
        if (t) { e.preventDefault(); t.scrollIntoView({ behavior: 'smooth', block: 'start' }); history.replaceState(null, '', '#' + id); }
      });
    });
    // Scrollspy
    const tocLinks = new Map();
    document.querySelectorAll('.toc-item').forEach(a => tocLinks.set(a.getAttribute('href').slice(1), a));
    const io = new IntersectionObserver((entries) => {
      entries.forEach(en => {
        const link = tocLinks.get(en.target.id);
        if (!link) return;
        if (en.isIntersecting) { tocLinks.forEach(l => l.classList.remove('active')); link.classList.add('active'); }
      });
    }, { rootMargin: '-40% 0px -55% 0px', threshold: 0 });
    document.querySelectorAll('.post-card').forEach(el => io.observe(el));
    // Copy feed URL
    document.querySelectorAll('[data-copy]').forEach(btn => {
      btn.addEventListener('click', async () => {
        const text = btn.getAttribute('data-copy');
        try { await navigator.clipboard.writeText(text); const o = btn.textContent; btn.textContent = 'Copied'; setTimeout(() => btn.textContent = o, 1400); } catch(e) {}
      });
    });
    // Mobile nav toggle
    const menuBtn = document.querySelector('.menu-btn');
    const mobileNav = document.getElementById('mobile-nav');
    if (menuBtn && mobileNav) {
      const closeNav = () => {
        mobileNav.setAttribute('hidden', '');
        menuBtn.setAttribute('aria-expanded', 'false');
      };
      menuBtn.addEventListener('click', () => {
        const open = mobileNav.hasAttribute('hidden');
        if (open) {
          mobileNav.removeAttribute('hidden');
          menuBtn.setAttribute('aria-expanded', 'true');
        } else {
          closeNav();
        }
      });
      // Close on link click
      mobileNav.querySelectorAll('a').forEach(link => {
        link.addEventListener('click', closeNav);
      });
      // Close on outside click
      document.addEventListener('click', (e) => {
        if (!menuBtn.contains(e.target) && !mobileNav.contains(e.target)) {
          closeNav();
        }
      });
    }
  </script>
</body>
</html>
`;

/* ------------------------------ FEEDS ------------------------------ */

const rss =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/">\n` +
  `  <channel>\n` +
  `    <title>StarStore Insights</title>\n` +
  `    <link>${SITE}/blog/</link>\n` +
  `    <atom:link href="${SITE}/blog/rss.xml" rel="self" type="application/rss+xml" />\n` +
  `    <description>Guides, updates, and expert insights on Telegram Stars and the StarStore platform.</description>\n` +
  `    <language>en-us</language>\n` +
  `    <lastBuildDate>${new Date(latestDate).toUTCString()}</lastBuildDate>\n` +
  `    <generator>StarStore blog builder</generator>\n` +
  sorted
    .map(
      (p) =>
        `    <item>\n` +
        `      <title>${escape(p.title)}</title>\n` +
        `      <link>${postUrl(escape(p.slug))}</link>\n` +
        `      <guid isPermaLink="false">${SITE}/blog/${escape(p.slug)}</guid>\n` +
        `      <pubDate>${new Date(p.date).toUTCString()}</pubDate>\n` +
        `      <description>${escape(p.description)}</description>\n` +
        p.tags.map((t) => `      <category>${escape(t)}</category>\n`).join('') +
        `      <content:encoded><![CDATA[${p.bodyHtml}]]></content:encoded>\n` +
        `    </item>\n`,
    )
    .join('') +
  `  </channel>\n</rss>\n`;

const atom =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<feed xmlns="http://www.w3.org/2005/Atom">\n` +
  `  <title>StarStore Insights</title>\n` +
  `  <subtitle>Guides, updates, and expert insights on Telegram Stars and the StarStore platform.</subtitle>\n` +
  `  <link href="${SITE}/blog/" />\n` +
  `  <link rel="self" type="application/atom+xml" href="${SITE}/blog/atom.xml" />\n` +
  `  <id>${SITE}/blog/</id>\n` +
  `  <updated>${new Date(latestDate).toISOString()}</updated>\n` +
  `  <author><name>StarStore Team</name><uri>${SITE}</uri></author>\n` +
  sorted
    .map(
      (p) =>
        `  <entry>\n` +
        `    <title>${escape(p.title)}</title>\n` +
        `    <link href="${postUrl(escape(p.slug))}" />\n` +
        `    <id>${SITE}/blog/${escape(p.slug)}</id>\n` +
        `    <updated>${new Date(p.date).toISOString()}</updated>\n` +
        `    <published>${new Date(p.date).toISOString()}</published>\n` +
        `    <summary>${escape(p.description)}</summary>\n` +
        p.tags.map((t) => `    <category term="${escape(t)}" />\n`).join('') +
        `    <content type="html"><![CDATA[${p.bodyHtml}]]></content>\n` +
        `  </entry>\n`,
    )
    .join('') +
  `</feed>\n`;

const postPageHtml = (p: BlogPost) => `<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Generated by src/blog/build.ts. Do not edit by hand. -->
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escape(p.title)} | StarStore</title>
  <meta name="description" content="${escape(p.description)}" />
  <link rel="canonical" href="${postUrl(p.slug)}" />
  <meta property="og:type" content="article" />
  <meta property="og:title" content="${escape(p.title)} | StarStore" />
  <meta property="og:description" content="${escape(p.description)}" />
  <meta property="og:url" content="${postUrl(p.slug)}" />
  <meta property="og:image" content="${SITE}/favicon.png" />
  <meta name="twitter:card" content="summary_large_image" />
  <link rel="stylesheet" href="/css/blog.css" />
  <link rel="icon" type="image/png" href="/favicon.png" />
</head>
<body id="top">
  <main class="main">
    <div class="container-narrow">
      <article class="post-card" itemscope itemtype="https://schema.org/BlogPosting">
        <meta itemprop="datePublished" content="${escape(p.date)}" />
        <meta itemprop="author" content="StarStore" />
        <header class="post-header">
          <div class="post-tags">${p.tags.map((t) => `<span class="tag">${escape(t)}</span>`).join('')}</div>
          <h1 class="post-title" itemprop="headline">${escape(p.title)}</h1>
          <p class="post-desc" itemprop="description">${escape(p.description)}</p>
          <div class="post-meta"><span><strong>StarStore Team</strong></span><span class="dot">·</span><time datetime="${escape(p.date)}">${fmtDate(p.date)}</time><span class="dot">·</span><span>${p.readMinutes} min read</span></div>
        </header>
        <div class="post-body prose-custom" itemprop="articleBody">${p.bodyHtml}</div>
        <footer class="post-footer"><a href="/blog/" class="link-soft">← Back to all posts</a><a href="https://t.me/TgStarStore_bot" class="link-cta">Open StarStore in Telegram →</a></footer>
      </article>
    </div>
  </main>
</body>
</html>
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_HTML, html, 'utf8');
writeFileSync(OUT_RSS, rss, 'utf8');
writeFileSync(OUT_ATOM, atom, 'utf8');
for (const p of sorted) {
  const dir = join(OUT_DIR, p.slug);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'index.html'), postPageHtml(p), 'utf8');
}
console.log(`✔ Generated ${OUT_HTML} (${sorted.length} posts)`);
console.log(`✔ Generated ${OUT_RSS}`);
console.log(`✔ Generated ${OUT_ATOM}`);
